# Generated by Django 3.1 on 2020-08-16 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20200815_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Користувач', 'verbose_name_plural': 'Користувачі'},
        ),
    ]
